### PR TITLE
EOS-25297 : fix compilation errors with gcc-8 for libfabric

### LINKED ISSUE #1119: libfab compilation error with gcc-8
When building with gcc-8 (using devtoolset-8 on CentOS 7):

```
$ scl enable devtoolset-8 bash
$ ./autogen.sh && ./configure && make -j4
...
net/libfab/libfab.c: In function 'libfab_handle_connect_request_events':
net/libfab/libfab.c:735:22: error: ':12345:' directive writing 7 bytes into a region of size between 3 and 50 [-Werror=format-overflow=]
   sprintf(buf, "%s@%s:12345:%d:%d",
                      ^~~~~~~
net/libfab/libfab.c:735:16: note: directive argument in the range [0, 65535]
   sprintf(buf, "%s@%s:12345:%d:%d",
                ^~~~~~~~~~~~~~~~~~~
net/libfab/libfab.c:735:16: note: directive argument in the range [0, 65534]
In file included from /usr/include/stdio.h:937,
                 from /tmp/rpmbuild/BUILD/cortx-motr-2.0.0/lib/user_space/trace.h:28,
                 from /tmp/rpmbuild/BUILD/cortx-motr-2.0.0/lib/trace.h:38,
                 from net/libfab/libfab.c:177:
/usr/include/bits/stdio2.h:33:10: note: '__builtin___sprintf_chk' output between 14 and 69 bytes into a destination of size 53
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
net/libfab/libfab.c:729:22: error: ':12345:' directive writing 7 bytes into a region of size between 3 and 50 [-Werror=format-overflow=]
   sprintf(buf, "%s@%s:12345:%d:*",
                      ^~~~~~~
net/libfab/libfab.c:729:16: note: directive argument in the range [0, 65535]
   sprintf(buf, "%s@%s:12345:%d:*",
                ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:937,
                 from /tmp/rpmbuild/BUILD/cortx-motr-2.0.0/lib/user_space/trace.h:28,
                 from /tmp/rpmbuild/BUILD/cortx-motr-2.0.0/lib/trace.h:38,
                 from net/libfab/libfab.c:177:
/usr/include/bits/stdio2.h:33:10: note: '__builtin___sprintf_chk' output between 14 and 65 bytes into a destination of size 53
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems to be a regression after https://github.com/Seagate/cortx-motr/pull/623.

### PR DESCRIPTION
**Pull request by andriytk**
Closes #1119.

# Problem Statement
Compilation with gcc-8 fails, see #1119 for details.

# Design
N/A

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [x] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

File: net/libfab/libfab.c [hunk 1]
```diff
@@ -727,19 +726,19 @@ static void libfab_straddr_gen(struct m0_fab__conn_data *cd, char *buf,
...
 	else
-		sprintf(buf, "%s@%s:12345:%d:%d",
+		snprintf(buf, len, "%s@%s:12345:%d:%d",
 			cd->fcd_iface == FAB_LO ? "0" : en->fen_addr,
 			cd->fcd_iface == FAB_LO ? "lo" : 
 			((cd->fcd_iface == FAB_TCP) ? "tcp" : "o2ib"),
 			cd->fcd_portal, cd->fcd_tmid);
 
-	M0_ASSERT(len >= strlen(buf));
+	M0_ASSERT(len > strlen(buf));
```
Comment (ivan-alekhin) [inline net/libfab/libfab.c:741]: I'm not sure if my suggestion fits into the scope of this patch, but what do you think about the following idea?

```c
int rc;
rc = snprintf(buf, len, ...);
...
M0_ASSERT(rc > 0);
M0_ASSERT_INFO(rc < len, "Net addr should not be truncated"
                            "(wanted %d, available %d)", rc, (int) len);
```

Comment (andriytk) [reply net/libfab/libfab.c]: I like your idea. And good catch of the bug!

But you probably meant `M0_ASSERT_INFO(rc >= len, ...)`?

Added. Thanks!

Comment (ivan-alekhin) [reply net/libfab/libfab.c]: I meant `rc < len`. As per the man page: "Thus, a return value of `size` or more means that the output was truncated". If we want to avoid truncation then we must ensure that the return value is less that `size`. Therefore, we must ensure that `rc < len`.

Comment (andriytk) [reply net/libfab/libfab.c]: Ah, you are right. Fixed, thanks!

**Review by ivan-alekhin — APPROVED** [review]

**Review by siningwuseagate — APPROVED** [review]

File: net/libfab/libfab.c [hunk 2]
```diff
@@ -532,15 +532,14 @@ static int libfab_ep_addr_decode_native(const char *ep_name, char *node,
 		++cp;
 	}
 
-	if (node_size < (n+1) || port_size < (strlen(cp)+1))
+	if (n+1 > node_size || strlen(cp)+1 > port_size)
```
[the remark this answers is not in the document]
Comment (andriytk) [reply net/libfab/libfab.c]: Ok, added.

File: net/libfab/libfab.c [hunk 3]
```diff
@@ -770,7 +774,7 @@ static uint32_t libfab_handle_connect_request_events(struct m0_fab__tm *tm)
 	if (rc >= (int)sizeof(struct fi_eq_cm_entry) && event == FI_CONNREQ) {
 		cm_entry = (struct fi_eq_cm_entry *)entry;
 		cd = (struct m0_fab__conn_data*)(cm_entry->data);
-		libfab_straddr_gen(cd, straddr, sizeof(straddr), &en);
+		libfab_straddr_gen(cd, straddr, ARRAY_SIZE(straddr), &en);
```
Comment (huanghua78) [inline net/libfab/libfab.c:777]: because the element size of `char` is one byte, so the `sizeof` has the same result of 'ARRAY_SIZE`.

But usually, we use sizeof to get the size of its memory consumption.

File: net/libfab/libfab_internal.h [hunk 4]
```diff
@@ -48,7 +48,7 @@ extern struct m0_net_xprt m0_net_libfab_xprt;
 
 #define LIBFAB_ADDR_LEN_MAX	INET6_ADDRSTRLEN
 #define LIBFAB_PORT_LEN_MAX	6
-#define LIBFAB_ADDR_STRLEN_MAX  (LIBFAB_ADDR_LEN_MAX + LIBFAB_PORT_LEN_MAX + 1)
+#define LIBFAB_ADDR_STRLEN_MAX  (LIBFAB_ADDR_LEN_MAX + LIBFAB_PORT_LEN_MAX + 32)
```
Comment (huanghua78) [inline net/libfab/libfab_internal.h:51]: Why is this change needed?

**Comment by huanghua78** [comment]
Please ask Motr libfab team to review this, @upendrapatwardhan ? and others?

**Review by upendrapatwardhan — APPROVED** [review]

File: net/libfab/libfab.c (hunk 3 above)
Comment (andriytk) [reply net/libfab/libfab.c:777]: String symbols can be several bytes, e.g. wchar_t... So it's always better to use ARRAY_SIZE() for strings, than sizeof().

File: net/libfab/libfab_internal.h (hunk 4 above)
Comment (andriytk) [reply net/libfab/libfab_internal.h:51]: From #1119:

```
net/libfab/libfab.c:735:22: error: ':12345:' directive writing 7 bytes into a region of size between 3 and 50 [-Werror=format-overflow=]
   sprintf(buf, "%s@%s:12345:%d:%d",
                      ^~~~~~~
```

`LIBFAB_ADDR_STRLEN_MAX` is used as the buffer length. It's obvious that `+ 1` in the old code is not enough to accommodate what is tried to be snprintf-ed here besides the `LIBFAB_ADDR_LEN_MAX` and `LIBFAB_PORT_LEN_MAX`. Increasing its size fixed it.

File: net/libfab/libfab.c (hunk 3 above)
Comment (huanghua78) [reply net/libfab/libfab.c:777]: Yes, you are right.

File: net/libfab/libfab_internal.h (hunk 4 above)
Comment (huanghua78) [reply net/libfab/libfab_internal.h:51]: I think this is required when we try to LNET format EP address in libfabric.

Thank you.

**Review by huanghua78 — APPROVED** [review]
