### PR TITLE
RM: fix remote debtors leakage

### LINKED ISSUE #298: m0d-confd process starts killing cpu after some time - connections leakage
On SAGE cluster the only configured confd process got stuck killing CPU with 100% consumption. m0trace log is full of the following lines:

```
2662840296390  4941007.836.524400  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad4413f10
2662840296391  4941007.836.524739  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad440d170
2662840296392  4941007.836.525108  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad4405790
2662840296393  4941007.836.525495  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad43feaf0
2662840296394  4941007.836.525861  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad43f7d70
2662840296395  4941007.836.526245  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad43f0ef0
2662840296396  4941007.836.526584  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad43ea170
2662840296397  4941007.836.526917  7f7d94ff8710  DEBUG   rpc/formation2.c:585:frm_fill_packet_from_item_sources   conn: 0x7f7ad43dd0f0
```

m0trace file - [sage-confd-kills-cpu-m0trace-af6819c.36917.zip](https://github.com/Seagate/cortx-motr/files/5695695/sage-confd-kills-cpu-m0trace-af6819c.36917.zip)

Versions:
* Motr - commit af6819c
* Hare - commit 571ae39

The cluster configuration file - [sage-proto-cdf.yaml.txt](https://github.com/Seagate/cortx-motr/files/5696147/sage-proto-cdf.yaml.txt)

### PR DESCRIPTION
**Pull request by andriytk**
**Background**: each Motr-process in the cluster (client or server) usually starts [`rconfc`](https://github.com/Seagate/cortx-motr/discussions/294) instance inside itself on startup to get the cluster configuration. `rconfc` takes the distributed read lock on the configuration from the main RM (Resource Manager) service which is usually run co-located with the main confd-service in the same m0d-process. This lock is revoked by the main confd-service when the configuration has to be updated (by taking the write-lock).  This way it is made sure that all Motr-processes in the cluster always have up to date configuration.

Now, for each rconfc read-lock RM-debtor instance is created by the main RM-service. This debtor creates the reverse rpc-session (and connection) also to each process requested the lock (so that the latter can be revoked by the main RM whenever needed).

**Problem**: currently, the debtor instance is not cleaned up (along with its reverse session/connection) when the remote process stops its rconfc instance and cancels the lock voluntarily. As a result, the debtors and reverse connections get accumulated over the time in the main m0d-confd process (which runs the main RM-service also) leaking the memory and wasting CPU resources.

**Solution**: add loans reference counter to the debtor and destroy debtor instance when: 1) the counter drops to zero and 2) the debtor has no pending incoming requests for loans.

Closes #298.

### CODE REVIEW

**Comment by andriytk** [comment]
Note: rm-ut is not passing yet. But I've checked it on the single-node cluster by the logs - the leakage is fixed.

**Comment by andriytk** [comment]
Successfully deployed patched Motr on the SAGE-cluster and restarted the cluster - so far so good...

**Comment by andriytk** [comment]
Looks like after several successful rconfc start-stop iterations something gets stuck and rconfc cannot finish the start anymore in the Motr processes. Something to be investigated further...

**Comment by andriytk** [comment]
Although rm-ut passes with the latest fixup, but still - rm-ut:flock gets stuck sometimes.

File: ha/entrypoint.c [hunk 1]
```diff
@@ -489,7 +489,7 @@ static void ha_entrypoint_client_replied(struct m0_rpc_item *item)
 	}
 	/* XXX TODO Handle rpc errors. */
 	m0_fom_wakeup(&ecl->ecl_fom);
-	m0_rpc_item_put(item); /* XXX Bug if rc != 0 ? */
+	m0_rpc_item_put(item);
```
Comment (huanghua78) [inline ha/entrypoint.c:492]: What if the `rc` is not zero?
There would be no matching m0_rpc_item_get() for this put.
Do you think we need:
```
if (rc == 0) {
        m0_rpc_item_put(item);
}
```

File: rpc/service.c [hunk 2]
```diff
@@ -192,15 +192,63 @@ m0_rpc_service_reverse_session_get(struct m0_reqh_service   *service,
...
+	revc = container_of(rlk, struct m0_reverse_connection, rcf_rlink);
+
+	M0_SET0(&revc->rcf_disc_wait);
+	if (revc->rcf_rlink.rlk_connected) {
+		m0_clink_init(&revc->rcf_disc_wait, rev_conn_disconnected_cb);
+		revc->rcf_disc_wait.cl_is_oneshot = true;
+		m0_rpc_link_disconnect_async(&revc->rcf_rlink,
+				m0_time_from_now(M0_REV_CONN_TIMEOUT, 0),
+				&revc->rcf_disc_wait);
+	}
```
Comment (huanghua78) [inline rpc/service.c:237]: Is there a possibility that this function and the next cleanup() have some race conditions?
So they will be trying to call m0_rpc_link_disconnect_async() at the same time?

File: ha/entrypoint.c (hunk 1 above)
Comment (andriytk) [reply ha/entrypoint.c:492]: @huanghua78, the above get() is for `item->ri_reply`, but this put() is for `item` - they are not matching in any case.

File: rpc/service.c (hunk 2 above)
Comment (andriytk) [reply rpc/service.c:237]: Yes. Calling disconnect_async() at the same time - is probably not a problem. (Is it?) But cleaning up at the same time is problematic. That's why `m0_rpc_service_reverse_sessions_cleanup()` is called under the locality0 lock and `rev_conn_free()` is called as an AST under locality0.

**Comment by huanghua78** [comment]
@andriytk can you ask someone else to review this PR more?

**Comment by andriytk** [comment]
@huanghua78 yes, I've asked @nikitadanilov.

**Comment by madhavemuri** [comment]
@andriytk : What if during new session/connection establish if we can identify the duplicate/stale connections and removes them from the list, won't that be possible here ?

**Comment by andriytk** [comment]
The problem with the current patch is that it does not work well with multiple loan requests from the same remote process. Here is what happening at rm-rcredits-ut:starvation which fails:

1. The loan is taken by rm_remote and is added to ro_sublet list.
2. Another request for the same credit comes from the same client process so the new rm_remote is not created.
3. Revoke outgoing request is sent, revokes the loan, removes it from ro_sublet list and destroys it. The credit is added to the cached list.
4. rm_remote is destroyed as the loan was the last one having the reference to it.
5. The new request tries to take the freed credit, but fails because rm_remote instance is not available any longer.

**Comment by andriytk** [comment]
@madhavemuri I thought about such kind of garbage collection too. But the problem is - there is no easy way to determine which debtor rm_remotes are still needed and which are not without adding some reference counters into them.

**Comment by andriytk** [comment]
All UTs are passing now (including rm-rcredits-ut:starvation) after addition of reference counting for the pending rm_incoming requests also into rm_remote (debtor). But still, rm-ut:flock gets sometimes stuck in a deadlock. The work is still in progress.

**Comment by andriytk** [comment]
All UTs are passing now (including rm-rcredits-ut:starvation) after addition of reference counting for the pending rm_incoming requests also into rm_remote (debtor). The intermittent deadlock on rm-ut:flock is fixed also.

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227/>Motr#227</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>0</td><td><details><summary>:file_folder:</summary><p></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>58</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></p></details></td></tr><tr><td>Total</td><td>63</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/227//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by andriytk** [comment]
I'm checking the patch on the SAGE cluster also...

**Comment by andriytk** [comment]
The patch on the SAGE cluster is working fine since last Sat (3 days already).

**Comment by andriytk** [comment]
Still works fine (4 days so far):

```
$ ps aux | sed -n -e 1p -e '/m0d.*conf[d]/p'
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     40288 40.9  0.1 27378892 2536316 ?    SLsl Jan09 2240:21 /usr/bin/m0d -e lnet:172.18.1.1@o2ib:12345:2:1 -A linuxstob:/var/log/seagate/motr/addb/m0d-0x7200000000000001:0x9/addb-stobs -f <0x7200000000000001:0x9> -T linux -S stobs -D db -m 524288 -q 512 -n 82 -k 2097152 -K 536870912 -p 134217728 -C 524288 -N 83886080 -s 2097152 -y 300 -Y 300 -E 512 -c /etc/motr/confd.xc -H 172.18.1.1@o2ib:12345:1:1 -U -r 1073741824
```

**Comment by huanghua78** [comment]
What is the status of this PR?
Waiting for review from @nikitadanilov ?

**Comment by andriytk** [comment]
@huanghua78 yes.

**Comment by madhavemuri** [comment]
This patch has also deployed on 36 node VM setup by @yatin-mahajan  and found it to be working fine.
https://jts.seagate.com/browse/EOS-16838?focusedCommentId=2035691

File: rm/rm.c [hunk 3]
```diff
@@ -2618,33 +2677,30 @@ M0_INTERNAL int m0_rm_owner_loan_debit(struct m0_rm_owner *owner,
...
-			if (rc == 0) {
-				if (credit_is_empty(&remnant_loan->rl_credit)) {
-					m0_rm_ur_tlist_move(&remove_list, cr);
-					m0_rm_ur_tlist_add(&remove_list,
-						&remnant_loan->rl_credit);
-				} else
-					m0_rm_ur_tlist_move(&retain_list, cr);
-			}
-		}
+	    if (cr->cr_ops->cro_intersects(&paid_loan->rl_credit, cr)) {
```
Comment (AbhishekSahaSeagate) [inline rm/rm.c:2686]: Can you add some comments explaining in which cases do we move the credits to the retain/remove lists?

File: rpc/service.c [hunk 4]
```diff
@@ -192,15 +192,67 @@ m0_rpc_service_reverse_session_get(struct m0_reqh_service   *service,
...
+	revc->rcf_free_ast = (struct m0_sm_ast){
+		.sa_cb    = &rev_conn_free,
+		.sa_datum = revc,
+	};
+	m0_sm_ast_post(m0_locality0_get()->lo_grp, &revc->rcf_free_ast);
+	return true;
+}
+
+M0_INTERNAL void
+m0_rpc_service_reverse_session_put(struct m0_rpc_session *sess)
```
Comment (AbhishekSahaSeagate) [inline rpc/service.c:220]: [Question]
When and where is this function called from?

Comment (andriytk) [reply rpc/service.c:220]:
```
$ gg m0_rpc_service_reverse_session_put
rm/rm.c:1395:           m0_rpc_service_reverse_session_put(sess);
```
at `remote_free()` when the debtor has no more loans and no more pending incoming requests for them.

File: rm/rm.c (hunk 3 above)
Comment (andriytk) [reply rm/rm.c:2686]: We only need to to retain the remnant loan and only when it's not empty, right? That's all.

File: rm/rm.h [hunk 5]
```diff
@@ -764,6 +762,19 @@ struct m0_rm_remote {
 	 * resource manager service.
 	 */
 	struct m0_cookie        rem_cookie;
+	/**
+	 * Reference counter for the loans taken by this remote debtor.
+	 * When the last loan is released - rm_remote instance is freed.
```
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.h:767]: Agree, fixed. Thanks.

File: rpc/service.c (hunk 4 above)
Comment (AbhishekSahaSeagate) [reply rpc/service.c:220]: Thanks

**Review by AbhishekSahaSeagate — APPROVED** [review]
Seems fine to me.

File: rm/rm.c [hunk 6]
```diff
@@ -2747,24 +2805,25 @@ M0_INTERNAL int m0_rm_loan_settle(struct m0_rm_owner *owner,
...
-						 "rc [%d]\n", rc);
-		}
-	} else
-		M0_LOG(M0_ERROR, "credit allocation failed: rc [%d]\n", rc);
+             granted_maybe_reserve(&loan->rl_credit, cached);
+	if (rc != 0) {
+		M0_LOG(M0_ERROR, "credit allocation failed: rc=%d", rc);
+		return M0_RC(rc);
+	}
+
```
Comment (nikitadanilov) [inline rm/rm.c:2813]: How is this related to the purpose of the patch?

File: rm/rm_foms.c [hunk 7]
```diff
@@ -585,6 +586,11 @@ static int request_pre_process(struct m0_fom *fom,
 			m0_rm_incoming_fini(&rfom->rf_in.ri_incoming);
 			goto err;
 		}
+		rfom->rf_in.ri_incoming.rin_remote = debtor;
+		cnt = m0_ref_read(&debtor->rem_incomings);
+		M0_LOG(M0_DEBUG, "rm_remote=%p incomings: %d -> %d",
+		       debtor, cnt, cnt + 1);
+		m0_ref_get(&debtor->rem_incomings);
```
Comment (nikitadanilov) [inline rm/rm_foms.c:593]: Please introduce helper functions loan_{get,put}() and use them.

Comment (nikitadanilov) [inline rm/rm_foms.c:593]: Please introduce helper functions loan_{get,put}() and use them.

File: rm/rm.h [hunk 8]
```diff
@@ -764,6 +762,21 @@ struct m0_rm_remote {
...
+	 * Note: this should not be used for creditors whose life-cycle
+	 *       does not depend on the number of credited loans.
+	 */
+	struct m0_ref           rem_loans;
+	/**
+	 * Reference counter for pending rm_incoming requests.
+	 * rm_remote instance can be freed only if there are no pending
+	 * incoming requests on it (see rem_loans also).
+	 */
+	struct m0_ref           rem_incomings;
```
Comment (nikitadanilov) [inline rm/rm.h:779]: Why do we need 2 separate reference counters? Wouldn't a single counter be sufficient?

Note that documentation is contradictory: first, it claims that a loan can be freed when there are no pending incoming requests *and* no unsettled loans, then that only "no pending incoming requests" condition is sufficient.

File: rm/rm.h [hunk 9]
```diff
@@ -62,23 +61,25 @@
...
- *       access mode bits (read, write);
+ *   - file data. Credits to use this resource are extents in the file plus
+ *     access mode bits (read, write);
  *
- *     - free storage space on a server (a "grant" in Lustre
- *       terminology). Credit to use this resource is a reservation of a given
- *       number of bytes;
+ *   - free storage space on a server (a "grant" in Lustre
+ *     terminology). Credit to use this resource is a reservation of a given
+ *     number of bytes;
```
Comment (nikitadanilov) [inline rm/rm.h:72]: What is being fixed in these formatting changes?

File: rm/rm_ha.c [hunk 10]
```diff
@@ -416,8 +416,12 @@ M0_INTERNAL void m0_rm_ha_unsubscribe(struct m0_rm_ha_tracker *tracker)
...
 	struct m0_conf_obj *obj;
 
-	if (m0_clink_is_armed(&tracker->rht_conf_exp))
-		m0_clink_cleanup_locked(&tracker->rht_conf_exp);
+	if (m0_clink_is_armed(&tracker->rht_conf_exp)) {
+		if (m0_chan_is_locked(tracker->rht_conf_exp.cl_chan))
+			m0_clink_cleanup_locked(&tracker->rht_conf_exp);
+		else
+			m0_clink_cleanup(&tracker->rht_conf_exp);
+	}
```
Comment (nikitadanilov) [inline rm/rm_ha.c:424]: A situation with data structure can be either locked or unlocked is unusual. Please document why and when is this possible.

Comment (nikitadanilov) [inline rm/rm_ha.c:424]: A situation with data structure can be either locked or unlocked is unusual. Please document why and when is this possible.

**Review by nikitadanilov — CHANGES_REQUESTED** [review]
Looks good except for unrelated style and formatting changes.

File: rm/rm.c [hunk 11]
```diff
@@ -1069,6 +1070,7 @@ M0_INTERNAL void m0_rm_incoming_init(struct m0_rm_incoming      *in,
 	in->rin_type   = type;
 	in->rin_policy = policy;
 	in->rin_flags  = flags;
+	in->rin_remote = NULL;
```
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:1073]: Right, will fix.

File: rm/rm.c [hunk 12]
```diff
@@ -1107,6 +1109,12 @@ M0_INTERNAL void m0_rm_incoming_fini(struct m0_rm_incoming *in)
 	 * to. Owner may appear lockable at the beginning, but being already
 	 * finalised when it is time to unlock sm.
 	 */
+	if (in->rin_remote != NULL) {
```
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:1112]: Right, will fix.

File: rm/rm.c [hunk 13]
```diff
@@ -2003,44 +2058,48 @@ static void incoming_check(struct m0_rm_incoming *in)
...
-		 * @todo
-		 * Here we introduce "thundering herd" problem, potentially
-		 * waking up all requests waiting for reserved credit.
-		 * It is necessary, because rio_conflict() won't be called for
-		 * 'in' if waiting requests are not woken up.
-		 */
-		barrier_pins_del(in);
+		M0_LEAVE();
+		return;
+	}
```
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:2063]: It is related, but it goes as a separate patch in this PR (see 757b634372f626e4dcc742e6d0e7926a31bfdc48). Sorry for the inconvenience.

File: rm/rm.c [hunk 14]
```diff
@@ -2618,33 +2681,30 @@ M0_INTERNAL int m0_rm_owner_loan_debit(struct m0_rm_owner *owner,
...
 	M0_PRE(owner != NULL);
 	M0_PRE(paid_loan != NULL);
-	M0_ENTRY("credit: %llu",
+	M0_ENTRY("loan=%p credit: %llu", paid_loan,
 			(long long unsigned) paid_loan->rl_credit.cr_datum);
 
 	m0_rm_ur_tlist_init(&retain_list);
 	m0_rm_ur_tlist_init(&remove_list);
 	m0_tl_for (m0_rm_ur, list, cr) {
-		if (!cr->cr_ops->cro_intersects(&paid_loan->rl_credit, cr))
```
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:2627]: There are too many indentations in this place. Making one less indentation by using 4-space one in this one line only greatly improves the readability in the whole block below. Can't we allow such exceptions sometimes for the sake of the overall benefit in code neatness and readability?

File: rm/rm.c (hunk 6 above)
Comment (andriytk) [reply rm/rm.c:2813]: See commit c4b8e1485ccabad6566042a566b5889fd6c99c32. It helped me to understand the code when I was working on the patch.

File: rm/rm.h (hunk 9 above)
Comment (andriytk) [reply rm/rm.h:72]: Doxygen-generated doc generates fixed-style text for these items instead of normal bulletted list without this change.

File: rm/rm.h (hunk 8 above)
Comment (andriytk) [reply rm/rm.h:779]: Unfortunately, not. All loans can be taken from the debtor, but there might be still some pending requests from it (he still might want the loans). In this case we don't want to free the debtor.

The 2nd comment states: "rm_remote instance can be freed only if there are no pending incoming requests on it". It does not claim that it should be a sufficient condition to free it, but only that it is a necessary condition.

File: rm/rm_foms.c (hunk 7 above)
Comment (andriytk) [reply rm/rm_foms.c:593]: Will do, thanks.

Comment (andriytk) [reply rm/rm_foms.c:593]: Ah, now I recall why I didn't do it in the 1st place: I wanted the calling function to be visible in the log, not loan_{get,put}() (which would not be of very much use). Will do it with a macro...

File: rm/rm_ha.c (hunk 10 above)
Comment (andriytk) [reply rm/rm_ha.c:424]: Without this it panics on running `rm-ut`:

```
$ ./scripts/m0 run-ut -t rm-ut
----- run_ut -t rm-ut -----
rm-ut 
  api                                             0.00 sec    4 KiB
  lcredits                                        0.00 sec   18 KiB
  fop-funcs                                       0.00 sec   35 KiB
  fom-funcs                                       0.32 sec   82 MiB
  rmsvc                                           1.28 sec  179 MiB
  flock  motr[02222]:  3510  FATAL  [lib/assert.c:50:m0_panic]  panic: (m0_chan_is_locked(link->cl_chan)) at m0_clink_cleanup_locked() (lib/chan.c:321)  [git: sage-base-1.0-172-gc0812e366] /var/motr/m0ut/m0trace.2222
Motr panic: (m0_chan_is_locked(link->cl_chan)) at m0_clink_cleanup_locked() lib/chan.c:321 (errno: 0) (last failed: none) [git: sage-base-1.0-172-gc0812e366] pid: 2222  /var/motr/m0ut/m0trace.2222
...
$ sudo gdb /var/crash/core.0.lt-m0ut.2222 
...
(gdb) bt
#0  0x00007f8ac8b10387 in raise () from /lib64/libc.so.6
#1  0x00007f8ac8b11a78 in abort () from /lib64/libc.so.6
#2  0x00007f8aca367e25 in m0_arch_panic (c=c@entry=0x7f8aca7efc00 <__pctx.5769>, ap=ap@entry=0x7f8a193f3588)
    at lib/user_space/uassert.c:131
#3  0x00007f8aca356ee4 in m0_panic (ctx=ctx@entry=0x7f8aca7efc00 <__pctx.5769>) at lib/assert.c:52
#4  0x00007f8aca3586ea in m0_clink_cleanup_locked (link=link@entry=0x7f8ac00f5780) at lib/chan.c:321
#5  0x00007f8aca3d6350 in m0_rm_ha_unsubscribe (tracker=tracker@entry=0x7f8ac00f5728) at rm/rm_ha.c:420
#6  0x00007f8aca3d6382 in m0_rm_ha_unsubscribe_lock (tracker=tracker@entry=0x7f8ac00f5728) at rm/rm_ha.c:441
#7  0x00007f8aca3cdd8e in m0_rm_remote_fini (rem=rem@entry=0x7f8ac00f5640) at rm/rm.c:1435
#8  0x00007f8aca3cde8e in remote_free (rem=0x7f8ac00f5640) at rm/rm.c:1377
#9  0x00007f8aca3cdac4 in m0_rm_loan_fini (loan=loan@entry=0x7f8aa808a768) at rm/rm.c:1264
#10 0x00007f8aca3cdb2e in m0_rm_outgoing_fini (out=out@entry=0x7f8aa808a760) at rm/rm.c:1169
#11 0x00007f8aca3cf423 in owner_balance (o=o@entry=0x7f8aa80871b0) at rm/rm.c:1951
#12 0x00007f8aca3d1220 in m0_rm_outgoing_complete (og=og@entry=0x7f8aa808a760) at rm/rm.c:2446
#13 0x00007f8acba40d47 in outreq_fini (rc=<optimized out>, outreq=0x7f8aa808a760) at /data/motr/rm/rm_fops.c:269
#14 rm_revoke_ast (grp=0x7f8aa8086ce0, ast=0x7f8aa808a800) at /data/motr/rm/rm_fops.c:494
#15 0x00007f8aca3f12c2 in m0_sm_asts_run (grp=grp@entry=0x7f8aa8086ce0) at sm/sm.c:169
#16 0x00007f8aca3f133d in m0_sm_group_lock (grp=grp@entry=0x7f8aa8086ce0) at sm/sm.c:86
#17 0x00007f8aca3d26f4 in credit_processor (rt=0x7f8aa8086c70) at rm/rm.c:702
#18 0x00007f8aca35df8e in m0_thread_trampoline (arg=arg@entry=0x7f8aa8086db8) at lib/thread.c:117
#19 0x00007f8aca368abd in uthread_trampoline (arg=0x7f8aa8086db8) at lib/user_space/uthread.c:98
#20 0x00007f8ac9ae7ea5 in start_thread () from /lib64/libpthread.so.0
#21 0x00007f8ac8bd896d in clone () from /lib64/libc.so.6
(gdb) 
```

Comment (andriytk) [reply rm/rm_ha.c:424]: Another panic from m0d process:

```
#3  0x00007ff94f75cee4 in m0_panic (ctx=ctx@entry=0x7ff94fbf5c00 <__pctx.5769>) at lib/assert.c:52
#4  0x00007ff94f75e6ea in m0_clink_cleanup_locked (link=link@entry=0x7ff9440b5020) at lib/chan.c:321
#5  0x00007ff94f7dc350 in m0_rm_ha_unsubscribe (tracker=tracker@entry=0x7ff9440b4fc8) at rm/rm_ha.c:420
#6  0x00007ff94f7dc382 in m0_rm_ha_unsubscribe_lock (tracker=tracker@entry=0x7ff9440b4fc8) at rm/rm_ha.c:441
#7  0x00007ff94f7d3d8e in m0_rm_remote_fini (rem=rem@entry=0x7ff9440b4ee0) at rm/rm.c:1435
#8  0x00007ff94f7d3e8e in remote_free (rem=0x7ff9440b4ee0) at rm/rm.c:1377
#9  0x00007ff94f7d3ac4 in m0_rm_loan_fini (loan=loan@entry=0x7ff9440b5d20) at rm/rm.c:1264
#10 0x00007ff94f7d7777 in m0_rm_owner_loan_debit (owner=owner@entry=0x7ff9440b2f50, paid_loan=paid_loan@entry=0x7ff9440b4da0, 
    list=list@entry=0x7ff9440b3000) at rm/rm.c:2706
#11 0x00007ff94f7d8497 in m0_rm_loan_settle (owner=owner@entry=0x7ff9440b2f50, loan=loan@entry=0x7ff9440b4da0) at rm/rm.c:2804
#12 0x00007ff94f7d9a8e in cancel_process (fom=0x7ff9240536d0) at rm/rm_foms.c:778
#13 request_fom_tick (fom=0x7ff9240536d0, type=<optimized out>) at rm/rm_foms.c:667
#14 0x00007ff94f73205b in fom_exec (fom=0x7ff9240536d0) at fop/fom.c:785
#15 loc_handler_thread (th=0x2213cc0) at fop/fom.c:925
```

Comment (andriytk) [reply rm/rm_ha.c:424]: If we do only `m0_clink_cleanup()`:

```diff
@@ -417,10 +417,7 @@ M0_INTERNAL void m0_rm_ha_unsubscribe(struct m0_rm_ha_tracker *tracker)
        struct m0_conf_obj *obj;
 
        if (m0_clink_is_armed(&tracker->rht_conf_exp)) {
-               if (m0_chan_is_locked(tracker->rht_conf_exp.cl_chan))
-                       m0_clink_cleanup_locked(&tracker->rht_conf_exp);
-               else
-                       m0_clink_cleanup(&tracker->rht_conf_exp);
+               m0_clink_cleanup(&tracker->rht_conf_exp);
        }
        if (m0_clink_is_armed(&tracker->rht_clink)) {
                obj = M0_AMB(obj, tracker->rht_clink.cl_chan, co_ha_chan);
```

Another UT panics:

```
$ ./scripts/m0 run-ut -t rm-rcredits-ut
----- run_ut -t rm-rcredits-ut -----
rm-rcredits-ut 
  no-borrow-flag                                  0.76 sec  248 MiB
  simple-borrow                                   0.71 sec  231 MiB
  two-borrows-single-req                          0.72 sec  232 MiB
  borrow-revoke-single-req                        0.73 sec  232 MiB
  revoke-with-hop                                 0.70 sec  231 MiB
  revoke-conflicting-wait                         0.70 sec  231 MiB
  revoke-conflicting-try                          0.69 sec  231 MiB
  borrow-non-conflicting                          0.69 sec  231 MiB
  revoke-no-conflict-wait                         0.69 sec  231 MiB
  revoke-no-conflict-try                          0.67 sec  232 MiB
  borrow-held-no-conflict                         0.66 sec  232 MiB
  borrow-held-conflicting                         0.70 sec  232 MiB
  starvation                                      0.74 sec  232 MiB
  barrier                                         1.67 sec  232 MiB
  barrier-overcome-star                           0.70 sec  232 MiB
  barrier-overcome-chain                          0.69 sec  232 MiB
  barrier-same-time                               0.67 sec  232 MiB
  debtor-death                                    0.67 sec  231 MiB
  creditor-death  motr[05693]:  1bf0  FATAL  [lib/assert.c:50:m0_panic]  panic: (m0_mutex_is_not_locked(mutex)) at m0_mutex_lock() (lib/mutex.c:53)  [git: sage-base-1.0-172-gc0812e366] /var/motr/m0ut/m0trace.5693
Motr panic: (m0_mutex_is_not_locked(mutex)) at m0_mutex_lock() lib/mutex.c:53 (errno: 2) (last failed: none) [git: sage-base-1.0-172-gc0812e366] pid: 5693  /var/motr/m0ut/m0trace.5693
...
$ sudo gdb ut/.libs/lt-m0ut /var/crash/core.0.lt-m0ut.5693
...
(gdb) bt
#0  0x00007f510b9b1387 in raise () from /lib64/libc.so.6
#1  0x00007f510b9b2a78 in abort () from /lib64/libc.so.6
#2  0x00007f510d208e25 in m0_arch_panic (c=c@entry=0x7f510d6939c0 <__pctx.4982>, ap=ap@entry=0x7ffe75461c68)
    at lib/user_space/uassert.c:131
#3  0x00007f510d1f7ee4 in m0_panic (ctx=ctx@entry=0x7f510d6939c0 <__pctx.4982>) at lib/assert.c:52
#4  0x00007f510d1fe5f4 in m0_mutex_lock (mutex=0x7f5113313fb8 <rm_ctxs+79032>) at lib/mutex.c:53
#5  0x00007f510d1f8fbd in m0_chan_lock (ch=<optimized out>) at lib/chan.c:70
#6  0x00007f510d1f9709 in m0_clink_cleanup (link=link@entry=0x17b3640) at lib/chan.c:313
#7  0x00007f510d277350 in m0_rm_ha_unsubscribe (tracker=tracker@entry=0x17b35e8) at rm/rm_ha.c:420
#8  0x00007f510d277382 in m0_rm_ha_unsubscribe_lock (tracker=tracker@entry=0x17b35e8) at rm/rm_ha.c:441
#9  0x00007f510d26ed8e in m0_rm_remote_fini (rem=0x17b3500) at rm/rm.c:1435
#10 0x00007f510e8e4af5 in rm_ctx_server_windup (srv_id=srv_id@entry=SERVER_2) at rm/ut/rmut.c:287
#11 0x00007f510e8e4b99 in rm_ctx_server_owner_windup (srv_id=srv_id@entry=SERVER_2) at rm/ut/rmut.c:275
#12 0x00007f510e8dd61f in remote_credits_utfini () at rm/ut/rcredits.c:206
#13 0x00007f510e91ab9e in run_test (max_name_len=43, test=0x696368 <rm_rcredits_ut+5064>) at ut/ut.c:389
#14 run_suite (max_name_len=43, suite=0x694fa0 <rm_rcredits_ut>) at ut/ut.c:454
#15 tests_run_all (m=0x7f5118f55a80 <ut.12177>) at ut/ut.c:507
#16 m0_ut_run () at ut/ut.c:533
#17 0x0000000000404436 in main (argc=3, argv=0x7ffe75462578) at ut/m0ut.c:502
(gdb) 
```

Comment (andriytk) [reply rm/rm_ha.c]: @nikitadanilov, please review https://github.com/Seagate/cortx-motr/pull/304/commits/c87a2c396760bee4336419caf691c5e813a588b6 for this.

Comment (andriytk) [reply rm/rm_ha.c]: I'm only not sure whether it will work in case of the actual configuration expiration path, probably not:

```
m0_confc_expired_cb() ->
  m0_chan_broadcast_lock(&reqh->rh_conf_cache_exp) ->
    rm_ha_conf_expired_cb() ->
      m0_rm_ha_unsubscribe_lock() -> ...
```

Comment (andriytk) [reply rm/rm_ha.c]: @nikitadanilov, please review the updated patch for this at https://github.com/Seagate/cortx-motr/pull/304/commits/01162dad04f208ce81572a36acdecacdfae00c32.

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262/>Motr#262</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>11</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></p></details></td></tr><tr><td>Total</td><td>13</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/262//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

File: rm/rm.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:2627]: Let me try to fix that anyway...

[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:2627]: See https://github.com/Seagate/cortx-motr/pull/304/commits/13c846b7ff0befbe6f0ad86921a2d763dacb5da2.

**Comment by andriytk** [comment]
Now I see the `rm-rwlock-ut:two-read-locks` gets stuck, gdb gives the following stacks:

```
Thread 96 (Thread 0x7f78b0c68700 (LWP 7514)):
#0  0x00007f78b3c8054d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f78b3c7be9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f78b3c7bd68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f78b44faa29 in m0_arch_mutex_lock (mutex=mutex@entry=0x7f78ac148200) at lib/user_space/umutex.c:56
#4  0x00007f78b44ef5d8 in m0_mutex_lock (mutex=0x7f78ac148200) at lib/mutex.c:55
#5  0x00007f78b44e9fbd in m0_chan_lock (ch=<optimized out>) at lib/chan.c:70
#6  0x00007f78b44ea709 in m0_clink_cleanup (link=link@entry=0x7f78ac10ed00) at lib/chan.c:313
#7  0x00007f78b455fd6e in m0_rm_remote_fini (rem=rem@entry=0x7f78ac10ecf0) at rm/rm.c:1432
#8  0x00007f78b455fece in remote_free (rem=0x7f78ac10ecf0) at rm/rm.c:1377
#9  0x00007f78b455fac4 in m0_rm_loan_fini (loan=loan@entry=0x7f78ac1242e0) at rm/rm.c:1264
#10 0x00007f78b45637b7 in m0_rm_owner_loan_debit (owner=owner@entry=0xb565d70, paid_loan=paid_loan@entry=0x7f78ac1248d0, 
    list=list@entry=0xb565e20) at rm/rm.c:2717
#11 0x00007f78b45644d7 in m0_rm_loan_settle (owner=owner@entry=0xb565d70, loan=loan@entry=0x7f78ac1248d0) at rm/rm.c:2815
#12 0x00007f78b5bd105e in cancel_process (fom=0x7f78600fc680) at /data/motr/rm/rm_foms.c:778
#13 request_fom_tick (fom=0x7f78600fc680, type=<optimized out>) at /data/motr/rm/rm_foms.c:667
#14 0x00007f78b44be05b in fom_exec (fom=0x7f78600fc680) at fop/fom.c:785
#15 loc_handler_thread (th=0x107fcc0) at fop/fom.c:925
#16 0x00007f78b44eff8e in m0_thread_trampoline (arg=arg@entry=0x107fcc8) at lib/thread.c:117
#17 0x00007f78b44faabd in uthread_trampoline (arg=0x107fcc8) at lib/user_space/uthread.c:98
#18 0x00007f78b3c79ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f78b2d6a96d in clone () from /lib64/libc.so.6

Thread 94 (Thread 0x7f78b1c6a700 (LWP 7516)):
#0  0x00007f78b44f10c1 in m0_tlist_invariant (d=d@entry=0x7f78b49e9a80 <m0_owners_tl>, list=list@entry=0xb565d40) at lib/tlist.c:250
#1  0x00007f78b44f1422 in m0_tlist_head (d=d@entry=0x7f78b49e9a80 <m0_owners_tl>, list=list@entry=0xb565d40) at lib/tlist.c:191
#2  0x00007f78b455d6ee in rev_session_clink_cb (link=0x7f78ac10ed00) at rm/rm.c:1320
#3  0x00007f78b44ea547 in clink_signal (clink=clink@entry=0x7f78ac10ed00) at lib/chan.c:135
#4  0x00007f78b44ea5a2 in chan_signal_nr (chan=chan@entry=0x7f78ac1481d0, nr=0) at lib/chan.c:154
#5  0x00007f78b44ea63d in m0_chan_broadcast (chan=chan@entry=0x7f78ac1481d0) at lib/chan.c:174
#6  0x00007f78b44ea659 in m0_chan_broadcast_lock (chan=chan@entry=0x7f78ac1481d0) at lib/chan.c:181
#7  0x00007f78b457816a in rpc_link_fom_fini_common (fom=0x7f78ac147b08, connected=<optimized out>) at rpc/link.c:472
#8  0x00007f78b44be191 in fom_exec (fom=0x7f78ac147b08) at fop/fom.c:809
#9  loc_handler_thread (th=0x1080060) at fop/fom.c:925
#10 0x00007f78b44eff8e in m0_thread_trampoline (arg=arg@entry=0x1080068) at lib/thread.c:117
#11 0x00007f78b44faabd in uthread_trampoline (arg=0x1080068) at lib/user_space/uthread.c:98
#12 0x00007f78b3c79ea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f78b2d6a96d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f78c0460840 (LWP 7494)):
#0  0x00007f78b3c7fd2f in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007f78b3c7fe07 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007f78b3c7fea5 in sem_timedwait () from /lib64/libpthread.so.0
#3  0x00007f78b44f9257 in m0_semaphore_timeddown (semaphore=0x7ffec40efbe8, abs_timeout=<optimized out>) at lib/user_space/semaphore.c:126
#4  0x00007f78b44ea8f5 in m0_chan_timedwait (link=link@entry=0x7ffec40efbc0, abs_timeout=abs_timeout@entry=18446744073709551615)
    at lib/chan.c:356
#5  0x00007f78b4583a24 in m0_sm_timedwait (mach=mach@entry=0x127e130, states=states@entry=256, 
    deadline=deadline@entry=18446744073709551615) at sm/sm.c:401
#6  0x00007f78b455f279 in m0_rm_owner_timedwait (owner=owner@entry=0x127e130, state=state@entry=256, abs_timeout=18446744073709551615)
    at rm/rm.c:898
#7  0x00007f78b5bd5b6d in rm_ctx_server_owner_windup (srv_id=srv_id@entry=SERVER_3) at rm/ut/rmut.c:272
#8  0x00007f78b5bd7f14 in rwlock_two_read_locks_test () at rm/ut/rm_rwlock.c:475
#9  0x00007f78b5c0bb7e in run_test (max_name_len=43, test=0x6704e8 <rm_rwlock_ut+4744>) at ut/ut.c:389
#10 run_suite (max_name_len=43, suite=0x66f260 <rm_rwlock_ut>) at ut/ut.c:454
#11 tests_run_all (m=0x7f78c0246a80 <ut.12177>) at ut/ut.c:507
#12 m0_ut_run () at ut/ut.c:533
#13 0x0000000000404436 in main (argc=3, argv=0x7ffec40f0318) at ut/m0ut.c:502
```

File: rm/rm.h (hunk 8 above)
Comment (nikitadanilov) [reply rm/rm.h:779]: I still fail to understand how one reference counter is not enough.

What scenario would not work, if you replace all `m0_ref_get(&r->rem_{loans,incoming})` with `m0_ref_get(&r->rem_ref)` and all `m0_ref_put(&r->rem_{loans,incoming}, &func)` with `m0_ref_put(&r->rem_ref, &func)`?

File: rm/rm.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (nikitadanilov) [reply rm/rm.c:2627]: I'd argue that if standard indentation does not fit into 80 characters, the function is too complex and should be split.

File: rm/rm.h [hunk 15]
```diff
@@ -1948,6 +1948,38 @@ M0_INTERNAL void m0_rm_remote_init(struct m0_rm_remote *rem,
...
+
+#define m0_rm_remote_incoming_put(rem) \
+{ \
+	int cnt = m0_ref_read(&(rem)->rem_incomings); \
+	M0_LOG(M0_DEBUG, "rm_remote=%p incomings: %d -> %d", \
+	       (rem), cnt, cnt - 1); \
+	m0_ref_put(&(rem)->rem_incomings); \
+}
+
+#define m0_rm_remote_loan_get(rem) \
```
Comment (nikitadanilov) [inline rm/rm.h:1967]: Macro names must be all-capital.

**Review by nikitadanilov — CHANGES_REQUESTED** [review]

**Comment by nikitadanilov** [comment]
I left a top-level comment on the previous inspection, guess it fell through the cracks, let me repeat it:

Another point: m0_ref is a "lockless" reference counter that can be used outside of any lock. But in reality, correct lockless use is quite tricky. For one thing, it critically depends on the memory barriers in lib/refs.c.

I would like to do 2 things: (i) if it so happens that manipulations with ->rem_{incomings,loans} are already protected by some suitable lock, please use normal M0_CNT_{DEC,INC}() macros; (ii) document the locking rules for reference counters in rm/rm.h.

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263/>Motr#263</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>57</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></p></details></td></tr><tr><td>Total</td><td>63</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/263//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

File: rm/rm.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (andriytk) [reply rm/rm.c:2627]: Agree. Is it OK now?

File: rm/rm.h (hunk 15 above)
Comment (andriytk) [reply rm/rm.h:1967]: It will look ugly, but will do...

File: rm/rm.h (hunk 8 above)
Comment (andriytk) [reply rm/rm.h]: Fixed to one ref-counter, see https://github.com/Seagate/cortx-motr/pull/304/commits/990be42f16b64ce3a5b13ace4b310ca2fab1c0d4. Thanks for the hint!

File: rm/rm.h (hunk 15 above)
Comment (andriytk) [reply rm/rm.h]: Fixed.

**Comment by andriytk** [comment]
Got panic when running UTs in loop on 26th iteration:

```
rm-rcredits-ut 
  no-borrow-flag                                  0.70 sec  231 MiB
  simple-borrow                                   0.70 sec  231 MiB
  two-borrows-single-req                          0.70 sec  232 MiB
  borrow-revoke-single-req                        0.71 sec  232 MiB
  revoke-with-hop                                 0.71 sec  231 MiB
  revoke-conflicting-wait                         0.71 sec  231 MiB
  revoke-conflicting-try                          0.70 sec  231 MiB
  borrow-non-conflicting                          0.71 sec  232 MiB
  revoke-no-conflict-wait                         0.71 sec  231 MiB
  revoke-no-conflict-try                          0.71 sec  231 MiB
  borrow-held-no-conflict                         0.72 sec  232 MiB
  borrow-held-conflicting                         0.72 sec  232 MiB
  starvation  motr[06272]:  3530  FATAL  [lib/assert.c:50:m0_panic]  panic: (debtor != ((void *)0)) at m0_rm_borrow_commit() (rm/rm.c:1575)  [git: sage-base-1.0-172-gc0812e366] /var/motr/m0ut/m0trace.6272
Motr panic: (debtor != ((void *)0)) at m0_rm_borrow_commit() rm/rm.c:1575 (errno: 0) (last failed: none) [git: sage-base-1.0-172-gc0812e366] pid: 6272  /var/motr/m0ut/m0trace.6272
...
$ sudo gdb ut/.libs/lt-m0ut /var/crash/core.0.lt-m0ut.6272
...
Thread 1 (Thread 0x7f828d3f4700 (LWP 7403)):
#0  0x00007f834abf9387 in raise () from /lib64/libc.so.6
#1  0x00007f834abfaa78 in abort () from /lib64/libc.so.6
#2  0x00007f834c450fd5 in m0_arch_panic (c=c@entry=0x7f834c93ac80 <__pctx.15640>, ap=ap@entry=0x7f828d3f35a8)
    at lib/user_space/uassert.c:131
#3  0x00007f834c440094 in m0_panic (ctx=ctx@entry=0x7f834c93ac80 <__pctx.15640>) at lib/assert.c:52
#4  0x00007f834c4bb355 in m0_rm_borrow_commit (rem_in=rem_in@entry=0x7f8318051fc0) at rm/rm.c:1575
#5  0x00007f834db2753d in remote_incoming_complete (in=0x7f8318051fc0, rc=0) at /data/motr/rm/rm_foms.c:175
#6  0x00007f834c4b7ede in incoming_complete (in=in@entry=0x7f8318051fc0, rc=rc@entry=0) at rm/rm.c:2495
#7  0x00007f834c4b975f in incoming_check (in=0x7f8318051fc0) at rm/rm.c:2099
#8  owner_balance (o=o@entry=0x6d19a80) at rm/rm.c:1978
#9  0x00007f834c4ba400 in m0_rm_outgoing_complete (og=og@entry=0x7f8344109f30) at rm/rm.c:2458
#10 0x00007f834db29f0a in outreq_fini (rc=0, outreq=0x7f8344109f30) at /data/motr/rm/rm_fops.c:269
#11 rm_borrow_ast (grp=<optimized out>, ast=0x7f8344109fd0) at /data/motr/rm/rm_fops.c:457
#12 0x00007f834c4da482 in m0_sm_asts_run (grp=grp@entry=0xba773d0) at sm/sm.c:169
#13 0x00007f834c4da4fd in m0_sm_group_lock (grp=grp@entry=0xba773d0) at sm/sm.c:86
#14 0x00007f834c4bb8d4 in credit_processor (rt=0xba77360) at rm/rm.c:702
#15 0x00007f834c44713e in m0_thread_trampoline (arg=arg@entry=0xba774a8) at lib/thread.c:117
#16 0x00007f834c451c6d in uthread_trampoline (arg=0xba774a8) at lib/user_space/uthread.c:98
#17 0x00007f834bbd0ea5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007f834acc196d in clone () from /lib64/libc.so.6
```

**Comment by huanghua78** [comment]
Please also run ut in repetition mode and check, e.g. m0 run-ut -n 5 -t rm-rcredits-ut

**Comment by andriytk** [comment]
@huanghua78, yes - I usually run the UTs in while loop. But thanks for the `-n` option hint for run-ut, will try it.

**Comment by andriytk** [comment]
It passed more than 100 UTs iterations already without any issues with the latest fix:
```
$ while ./scripts/m0 run-ut -t rm-ut,rm-rwlock-ut,rm-rcredits-ut; do echo $((c++)); done
```

File: rm/rm.h [hunk 16]
```diff
@@ -1951,10 +1955,14 @@ M0_INTERNAL void m0_rm_remote_fini(struct m0_rm_remote *rem);
 
 #define M0_RM_REMOTE_PUT(rem) \
 { \
-	int cnt = m0_ref_read(&(rem)->rem_refcnt); \
+	int cnt; \
+	struct m0_mutex *mux = &rem->rem_resource->r_mutex; \
+	m0_mutex_lock(mux); \
+	cnt = m0_ref_read(&(rem)->rem_refcnt); \
```
Comment (nikitadanilov) [inline rm/rm.h:1961]: Store "rem" in a local variable to avoid multiple evaluations. Wrap the macro body in ({ ... }) — it's an expression, not statement.

Also, now that ->rem_refcnt is explicitly protected by a mutex, why do you need an atomic counter? Let's just use an integer with M0_CNT_{INC,DEC}().

**Review by nikitadanilov — CHANGES_REQUESTED** [review]

File: rm/rm.h (hunk 16 above)
Comment (andriytk) [reply rm/rm.h:1961]: It's explicitly protected by a mutex only on decrements. The increments still don't need any protection.

**Review by nikitadanilov — APPROVED** [review]

**Comment by andriytk** [comment]
@nikitadanilov thanks for the review! It was really helpful.
@huanghua78 let me groom the commits before landing...

**Review by ujjwalpl — APPROVED** [review]

**Comment by andriytk** [comment]
It seems ready for landing now.

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266/>Motr#266</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>15</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>24</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></p></details></td></tr><tr><td>Total</td><td>40</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/266//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267/>Motr#267</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>25</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>29</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></p></details></td></tr><tr><td>Total</td><td>59</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/267//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271/>Motr#271</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>58</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit/motr-single-node/62dix-repair-st-lookup-insert target=_blank>motr-single-node/62dix-repair-st-lookup-insert</a></p></details></td></tr><tr><td>Total</td><td>64</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/271//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274/>Motr#274</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>0</td><td><details><summary>:file_folder:</summary><p></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>59</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit/motr-single-node/62dix-repair-st-lookup-insert target=_blank>motr-single-node/62dix-repair-st-lookup-insert</a></p></details></td></tr><tr><td>Total</td><td>64</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/274//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275/>Motr#275</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>0</td><td><details><summary>:file_folder:</summary><p></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>59</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit/motr-single-node/62dix-repair-st-lookup-insert target=_blank>motr-single-node/62dix-repair-st-lookup-insert</a></p></details></td></tr><tr><td>Total</td><td>64</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/275//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

File: rm/rm_foms.c [hunk 17]
```diff
@@ -692,8 +695,12 @@ static int debtor_subscription_check(struct m0_fom *fom)
 	if (M0_IN(rfom->rf_sbscr.rhs_sm.sm_state,
 		  (RM_HA_SBSCR_FINAL, RM_HA_SBSCR_FAILURE))) {
 		if (rfom->rf_sbscr.rhs_sm.sm_rc != 0) {
-			M0_LOG(M0_DEBUG, "Can't subscribe to debtor with ep %s",
-			   m0_rm_remote_find(&rfom->rf_in)->rem_tracker.rht_ep);
+			struct m0_rm_remote *rem;
+			rem = m0_rm_remote_find(&rfom->rf_in);
```
Comment (huanghua78) [inline rm/rm_foms.c:699]: The `rem` might be NULL?
This should be ASSERTed or handled.

File: rm/ut/rmut.c [hunk 18]
```diff
@@ -274,16 +279,13 @@ void rm_ctx_server_windup(enum rm_server srv_id)
 {
 	struct m0_rm_owner *owner = rm_ctxs[srv_id].rc_test_data.rd_owner;
 	enum rm_server      cred_id = rm_ctxs[srv_id].creditor_id;
-	struct m0_reqh     *reqh = &rm_ctxs[srv_id].rc_rmach_ctx.rmc_reqh;
 
-	m0_chan_lock(&reqh->rh_conf_cache_exp);
```
Comment (huanghua78) [inline rm/ut/rmut.c:279]: Why is this needed in the original code? and what changes makes it not necessary now?

File: rm/rm.h [hunk 19]
```diff
@@ -315,6 +313,10 @@ struct m0_rm_resource {
 	 * with which local owners of credits to this resource communicates.
 	 */
 	struct m0_tl                     r_remote;
```
Comment (huanghua78) [inline rm/rm.h:315]: I propose to change this to plural form: r_remotes
Because this is a list of remote owners.

File: rm/rm.c [hunk 20]
```diff
@@ -1295,9 +1308,10 @@ static bool rev_session_clink_cb(struct m0_clink *link)
 			rem_rev_sess_clink, &rem_bob);
 	resource = remote->rem_resource;
 
-	if (m0_rpc_session_status(remote->rem_session) != 0)
-		/* The connection has failed. Stop further processing. */
+	if (m0_rpc_session_status(remote->rem_session) != 0) {
+		M0_LEAVE("remote rev_session status is not good");
```
Comment (huanghua78) [inline rm/rm.c:1312]: Is it necessary to have the "status" in the message?

Comment (huanghua78) [inline rm/rm.c:1312]: Is it necessary to have the "status" in the message?

File: rm/rm.c [hunk 21]
```diff
@@ -1506,6 +1571,10 @@ M0_INTERNAL int m0_rm_borrow_commit(struct m0_rm_remote_incoming *rem_in)
 		 (long long unsigned) INCOMING_CREDIT(in));
 	M0_PRE(in->rin_type == M0_RIT_BORROW);
 
+	debtor = m0_rm_remote_find(rem_in);
+	M0_ASSERT(debtor != NULL);
+	M0_RM_REMOTE_PUT(debtor);
```
Comment (huanghua78) [inline rm/rm.c:1576]: Should this be moved downward to LINE 1684? After the debtor is already used and not needed any longer.

File: rm/rm.c [hunk 22]
```diff
@@ -2618,33 +2693,31 @@ M0_INTERNAL int m0_rm_owner_loan_debit(struct m0_rm_owner *owner,
...
-			if (rc == 0) {
-				if (credit_is_empty(&remnant_loan->rl_credit)) {
-					m0_rm_ur_tlist_move(&remove_list, cr);
-					m0_rm_ur_tlist_add(&remove_list,
-						&remnant_loan->rl_credit);
-				} else
-					m0_rm_ur_tlist_move(&retain_list, cr);
-			}
-		}
+			continue;
```
Comment (huanghua78) [inline rm/rm.c:2703]: The following change is not only pure code re-org. It also changes the logic:

"m0_rm_ur_tlist_move(&retain_list, cr);" is not called.

File: rm/rm.c [hunk 23]
```diff
@@ -2618,33 +2693,31 @@ M0_INTERNAL int m0_rm_owner_loan_debit(struct m0_rm_owner *owner,
...
+
+		loan = bob_of(cr, struct m0_rm_loan, rl_credit, &loan_bob);
+
+		if (!m0_cookie_is_eq(&loan->rl_cookie, &paid_loan->rl_cookie))
+			continue;
```
Comment (huanghua78) [inline rm/rm.c:2708]: and here, the "cr" will not be moved to tail.

File: rm/rm.c (hunk 20 above)
Comment (andriytk) [reply rm/rm.c:1312]: Yes, it might be helpful, let me fix that...

File: rm/rm.c (hunk 21 above)
Comment (andriytk) [reply rm/rm.c:1576]: No, this put() is just to compensate the get() from find(). The needed get() was already taken earlier at request_pre_process(). Let me leave a comment about this...

File: rm/rm.c (hunk 22 above)
Comment (andriytk) [reply rm/rm.c:2703]: Yes, it is not need, is it?

File: rm/rm.c (hunk 23 above)
Comment (andriytk) [reply rm/rm.c:2708]: Yes, because we didn't move it out in the 1st place. There is no need to move cr from and back in if it not intersects with the debited credit, is it?

File: rm/rm.h (hunk 19 above)
Comment (andriytk) [reply rm/rm.h:315]: Makes sense, yes. Will do, thanks.

File: rm/rm_foms.c (hunk 17 above)
Comment (andriytk) [reply rm/rm_foms.c:699]: Agree, let me put an ASSERT here.

File: rm/ut/rmut.c (hunk 18 above)
Comment (andriytk) [reply rm/ut/rmut.c:279]: We now take the lock directly at m0_rm_remote_fini(), if needed.

File: rm/rm.c (hunk 23 above)
Comment (andriytk) [reply rm/rm.c:2708]: Please note: this change is not part of the fix, it goes in a separate commit - https://github.com/Seagate/cortx-motr/pull/304/commits/a720ed38d169bbeb16e171f9b999b471b1ca071d. And it's desirable that it's landed in the separate commit also.

File: rm/rm.c (hunk 22 above)
Comment (huanghua78) [reply rm/rm.c:2710]: agree.

File: rm/rm.c (hunk 23 above)
Comment (huanghua78) [reply rm/rm.c:2715]: agree.

**Review by huanghua78 — APPROVED** [review]
It looks fine to me.

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282/>Motr#282</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>0</td><td><details><summary>:file_folder:</summary><p></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>59</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit/motr-single-node/62dix-repair-st-lookup-insert target=_blank>motr-single-node/62dix-repair-st-lookup-insert</a></p></details></td></tr><tr><td>Total</td><td>64</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/282//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>
